FROM golang:1.19.2-alpine3.15

RUN apk update &&  apk add git
WORKDIR /go/src/app
COPY ./app ./
RUN export GO_ENV=/go/src/app/
RUN export GOOGLE_APPLICATION_CREDENTIALS="/go/src/app/service-account-file.json"

RUN go get -u github.com/ramya-rao-a/go-outline
RUN go install golang.org/x/tools/gopls@latest

# Hot Reload
RUN go install github.com/cosmtrek/air@v1.29.0

CMD ["air", "-c", ".air.toml"]